name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Use ReleaseDownloader action from Robin Raju ( https://github.com/marketplace/actions/release-downloader )
    - uses: robinraju/release-downloader@v1.9
      with:
        repository: "CQCL-DEV/QuantumOrigin.Library.Onboard"
        tag: "v2.1.0"
        #latest: true
        fileName: "qo_onboard_ubuntu-20.04_x64_Release-v*"
        tarBall: true
        extract: true
        out-file-path: ./qoo_latest

    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: make install_deps
      run: make install_deps
    - name: make build
      run: make build
    - name: make sample_code
      run: make sample_code
